### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by OndrejNepozitek** [OndrejNepozitek/ProceduralLevelGenerator#24]
### Description
It is needed to describe a format that will be used to load rooms and input graphs when using GUI. The format should probably support all the options that can be used through the api.

One way is to distinguish two types of files: one for map description (graph) and another one for room description.

Another open question is the language that should be used for the files. Candidates are for example YAML or JSON.

#### Room description proposal
```yaml
name: rectangles
default:
    doors-mode: 
        type: specific-positions
        door-positions:
          -  [[0,0], [0,3]]
rooms:
  - 
    name: 4-square
    shape: [[0,0], [0,4], [4,4], [4,0]]
    doors-mode: 
        type: overlap
        door-length: 1
        minimum-overlap: 1
  - 
    name: 2-4-rectangle
    shape: [[0,0], [0,4], [2,4], [2,0]]
```

#### Map description proposal
```yaml
default-room-shapes:
  - 
    set-name: rectangles
    rotate: true
    probability: 4
    scale: [2,2]
    exclude: [4-square]
  - 
    set-name: rectangles
    room-name: 4-square
    probability: 8
    scale: [2,2]
rooms:
  - name: 1
  - name: 2
  - name: 3
  -
     name: boss-room
     room-shapes:
       -
         set-name: boss-rooms-set
passages:
  - [1,2]
  - [2,3]
  - [3,boss-room]
```

### Steps to reproduce
None.

### Actual results
None.

### Expected results
None.

### Notes for the thesis
None.
